export const vehicles = [
  {
    id: "1",
    name: "Toyota Land Cruiser Prado",
    year: 2020,
    price: "MWK 45,000,000",
    mileage: "45,000 km",
    fuelType: "Diesel",
    image: "/toyota-land-cruiser-prado-black.jpg",
    condition: "Excellent" as const,
    transmission: "Automatic",
    engine: "2.8L Turbo Diesel",
    color: "Black",
    features: ["4WD", "Leather Seats", "Sunroof", "Navigation", "Reverse Camera"],
    description: "Well-maintained Toyota Land Cruiser Prado in excellent condition. Full service history available.",
  },
  {
    id: "2",
    name: "Honda Fit",
    year: 2019,
    price: "MWK 12,500,000",
    mileage: "62,000 km",
    fuelType: "Petrol",
    image: "/honda-fit-silver.jpg",
    condition: "Good" as const,
    transmission: "Automatic",
    engine: "1.3L Petrol",
    color: "Silver",
    features: ["AC", "Power Windows", "USB Port", "ABS"],
    description: "Reliable and fuel-efficient Honda Fit. Perfect for city driving.",
  },
  {
    id: "3",
    name: "Nissan X-Trail",
    year: 2018,
    price: "MWK 28,000,000",
    mileage: "78,000 km",
    fuelType: "Petrol",
    image: "/nissan-xtrail-white.jpg",
    condition: "Good" as const,
    transmission: "CVT",
    engine: "2.0L Petrol",
    color: "White",
    features: ["4WD", "Cruise Control", "Keyless Entry", "Climate Control"],
    description: "Spacious and comfortable Nissan X-Trail. Great for family trips.",
  },
  {
    id: "4",
    name: "Toyota Hilux",
    year: 2021,
    price: "MWK 38,000,000",
    mileage: "25,000 km",
    fuelType: "Diesel",
    image: "/toyota-hilux-grey.jpg",
    condition: "Excellent" as const,
    transmission: "Manual",
    engine: "2.4L Turbo Diesel",
    color: "Grey",
    features: ["4WD", "Tow Bar", "Roll Bar", "Diff Lock"],
    description: "Rugged Toyota Hilux pickup. Perfect for both work and adventure.",
  },
  {
    id: "5",
    name: "Mazda Demio",
    year: 2017,
    price: "MWK 9,800,000",
    mileage: "85,000 km",
    fuelType: "Petrol",
    image: "/mazda-demio-blue.jpg",
    condition: "Good" as const,
    transmission: "Automatic",
    engine: "1.3L Petrol",
    color: "Blue",
    features: ["AC", "Power Steering", "CD Player"],
    description: "Economical Mazda Demio in good condition. Low running costs.",
  },
  {
    id: "6",
    name: "Mercedes-Benz E-Class",
    year: 2019,
    price: "MWK 55,000,000",
    mileage: "38,000 km",
    fuelType: "Petrol",
    image: "/mercedes-benz-eclass-black.jpg",
    condition: "Excellent" as const,
    transmission: "Automatic",
    engine: "2.0L Turbo Petrol",
    color: "Black",
    features: ["Leather Interior", "Panoramic Roof", "Premium Sound", "Adaptive Cruise"],
    description: "Luxury Mercedes-Benz E-Class. Premium comfort and performance.",
  },
]

export const bookings = [
  {
    id: "BK001",
    customerName: "John Phiri",
    phone: "+265 991 234 567",
    vehicle: "Toyota Corolla - MA 1234",
    serviceType: "Full Service",
    date: "2024-12-15",
    time: "09:00 AM",
    status: "confirmed" as const,
    notes: "Customer requested oil filter replacement",
  },
  {
    id: "BK002",
    customerName: "Mary Banda",
    phone: "+265 888 765 432",
    vehicle: "Honda Fit - MA 5678",
    serviceType: "Oil Change",
    date: "2024-12-15",
    time: "11:00 AM",
    status: "in-progress" as const,
    notes: "",
  },
  {
    id: "BK003",
    customerName: "Peter Mwale",
    phone: "+265 999 111 222",
    vehicle: "Nissan X-Trail - MA 9012",
    serviceType: "Brake Inspection",
    date: "2024-12-16",
    time: "10:00 AM",
    status: "pending" as const,
    notes: "Customer mentioned squeaking noise",
  },
  {
    id: "BK004",
    customerName: "Grace Chirwa",
    phone: "+265 995 333 444",
    vehicle: "Mazda Demio - MA 3456",
    serviceType: "Tyre Alignment",
    date: "2024-12-14",
    time: "02:00 PM",
    status: "completed" as const,
    notes: "Also performed wheel balancing",
  },
]

export const leads = [
  {
    id: "L001",
    customerName: "Samuel Tembo",
    email: "samuel@email.com",
    phone: "+265 991 555 666",
    vehicleInterest: "Toyota Land Cruiser Prado",
    inquiryType: "Price Request",
    date: "2024-12-14",
    status: "new" as const,
    message: "Interested in this vehicle. Can we negotiate on price?",
  },
  {
    id: "L002",
    customerName: "Alice Nyirenda",
    email: "alice@email.com",
    phone: "+265 888 777 888",
    vehicleInterest: "Mercedes-Benz E-Class",
    inquiryType: "Test Drive",
    date: "2024-12-13",
    status: "contacted" as const,
    message: "Would like to schedule a test drive this weekend.",
  },
  {
    id: "L003",
    customerName: "David Phiri",
    email: "david@email.com",
    phone: "+265 999 888 999",
    vehicleInterest: "Honda Fit",
    inquiryType: "General Enquiry",
    date: "2024-12-12",
    status: "new" as const,
    message: "Is this still available? Can I view it tomorrow?",
  },
]

export const services = [
  {
    id: "oil-change",
    name: "Oil Change",
    description: "Complete oil and filter replacement with multi-point inspection",
    price: "From MWK 25,000",
    duration: "45 minutes",
    icon: "droplet",
  },
  {
    id: "full-service",
    name: "Full Service",
    description: "Comprehensive vehicle service including all fluids, filters, and safety checks",
    price: "From MWK 85,000",
    duration: "2-3 hours",
    icon: "wrench",
  },
  {
    id: "brake-check",
    name: "Brake Inspection",
    description: "Complete brake system inspection and pad replacement if needed",
    price: "From MWK 35,000",
    duration: "1 hour",
    icon: "disc",
  },
  {
    id: "tyre-alignment",
    name: "Tyre Alignment",
    description: "Professional wheel alignment and balancing for optimal handling",
    price: "From MWK 45,000",
    duration: "1.5 hours",
    icon: "circle",
  },
  {
    id: "diagnostics",
    name: "Engine Diagnostics",
    description: "Advanced computer diagnostics to identify and fix engine issues",
    price: "From MWK 55,000",
    duration: "1 hour",
    icon: "cpu",
  },
  {
    id: "ac-service",
    name: "AC Service",
    description: "Air conditioning system service and gas recharge",
    price: "From MWK 65,000",
    duration: "1.5 hours",
    icon: "wind",
  },
]
